### PR TITLE
Port of CoffeeScript files to Typescript files

### PR DESCRIPTION
**Pull request by ahnilica**
I ported the CoffeeScript files to TypeScript files, modified the makefile to support typescript builds, added a tsconfig.json file for managing TypeScript build settings, resolved all TypeScript build warnings and ran the Jasmine unit tests to verify that the new code is logically the same as the old code. Please let me know if there is anything else that needs to be done or if you have any issue with the work I've done, thank you.

### CODE REVIEW

**Comment by progrium** [comment]
Are all the `(<any>something)` necessary?

**Comment by ahnilica** [comment]
No, but I included them to resolve a bunch of transpiler warnings. Even if there are warnings, it will still generate the output .js files. The issue with that is that whole point of TypeScript is to see the useful warnings, so if it is overcrowded with non-useful warnings it would be easy to miss the useful ones. The warning resolved by (<any>x) is 'Property 'SOMETHING' does not exist on type 'object''. Basically, TypeScript doesn't like dynamic properties added to objects. By casting it to an 'any' type, we tell the transpiler that it's ok. Cleaner solutions would take significant code changes that I felt were out of scope of the work you expected from me.

**Comment by progrium** [comment]
Ok, that is reasonable. I'll take this and we can talk about cleaner solutions separately.

**Comment by ahnilica** [comment]
Sounds good. The cleaner solution would be to create custom types. When you cast an object to type 'any', you temporarily opt out of type checking the properties accessed on that object. For example, in lines 53 - 67 of duplex.js, the transpiler had an issue with the accessing of the properties 'id', 'more' and 'ext' on the object 'msg'. The fix for this would be to create a type that represents the message object and defines all the possible properties that can exist for that type. I can restructure the code in this way if you want, but it would take a lot more time than my original estimate.

**Pull request merged**
